### ISSUE TITLE
Provide first class support for azure pipelines

### ISSUE THREAD

**Issue by jimhester** [r-lib/covr#370]
Currently you can use the following to produce the coverage report

```yaml
- bash: R -q -e 'cov <- covr::package_coverage(); covr::to_cobertura(cov, "coverage.xml")'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
```

But it would be nice to at least have a `covr::azure_pipelines()` to do this in one call.
